// ============================================================================
// Central icon registry — maps the string icon names stored in campusData.ts
// to actual lucide-react components so data stays framework-agnostic.
// ============================================================================
import {
  DoorOpen,
  Laptop,
  Laptop2,
  Cpu,
  Cog,
  BookOpen,
  FlaskConical,
  FlaskRound,
  TestTube2,
  UtensilsCrossed,
  Coffee,
  CupSoda,
  Cross,
  HeartPulse,
  Theater,
  Drama,
  Trophy,
  ParkingCircle,
  Landmark,
  BedDouble,
  Accessibility,
  ShieldAlert,
  ShieldCheck,
  GraduationCap,
  Building2,
  PartyPopper,
  Briefcase,
  Microscope,
  Pill,
  Bot,
  Radio,
  Wrench,
  Award,
  Lightbulb,
  FileCheck,
  CreditCard,
  Bus,
  Bike,
  Car,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  DoorOpen,
  Laptop,
  Laptop2,
  Cpu,
  Cog,
  BookOpen,
  FlaskConical,
  FlaskRound,
  TestTube2,
  UtensilsCrossed,
  Coffee,
  CupSoda,
  Cross,
  HeartPulse,
  Theater,
  Drama,
  Trophy,
  ParkingCircle,
  Landmark,
  BedDouble,
  Accessibility,
  ShieldAlert,
  ShieldCheck,
  GraduationCap,
  Building2,
  PartyPopper,
  Briefcase,
  Microscope,
  Pill,
  Bot,
  Radio,
  Wrench,
  Award,
  Lightbulb,
  FileCheck,
  CreditCard,
  Bus,
  Bike,
  Car,
  Sparkles,
};

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Building2;
}
